package-lock.json, package.json, src/App.tsx, src/index.tsx, src/lib/GlobalStyle.ts, src/lib/theme.ts
GlobalStyle 생성 및 적용
- GlobalStyle 생성 및 적용
- font-size
- color
<br>
- closed #1
=> [Chore] #1/Global Style 적용

src/pages/Diagnosis.tsx, src/pages/DiagnosisList.tsx
결정적 진단 응답 api 호출
- 결정적 진단 응답 api 호출
<br/>
- closed #16
=> [Feat] 결정적 진단응답 api 호출

src/pages/MainPage.tsx
flexbox는 하위 요소의 높이값을 지정하지 않아도 남은 공간에 의해 자동으로 높이를 지정할 수 있음. 
따라서 flexbox로 남는 공간에 대해 MainImage 컴포넌트의 높이를 지정하고 
Image 컴포넌트가 안에 object-fit: contain으로 들어가도록 하면
남는 높이값에 따라 이미지의 높이가 비율왜곡 없이 정해짐.
https://stackoverflow.com/questions/90178/make-a-div-fill-the-height-of-the-remaining-screen-space
=> [fix] 이미지 크기 오류 수정

src/api/diagnose/fetcher.ts
- #68 
- fetcher에 배변이상 fetch 로직을 안 적어놨네요,,ㅎ 수정해서 다시 올립니다!
=> [Fix] 배변이상(설사) 로직 수정

src/api/diagnose/fetcher.ts, src/pages/diagnosis/answerButtons/index.tsx, src/pages/symptomType/index.tsx, src/utils/diagnosis.ts
- resolves #76 
- 아직 흉통 질문 API가 안 나와서, 예시 스키마를 resolve하는 promise로 모킹하였습니다.
- API 나오면 바로 반영해서 푸시하겠습니다!
=> [Feat] 흉통 질문 로직 구현

.github/.gitmessage
- 없음
- 커밋 템플릿 파일 추가
- 터미널 상에서 commit 템플릿 설정을 하고 싶다면 아래 명령어를 입력하면 git commit을 할 때마다 커밋 템플릿이 설정 됩니다.
- `git config --global commit.template .github/.gitmessage`
=> [Docs] 커밋 템플릿 생성

src/index.tsx
- resolves #99 
- merge 과정에서 query clienet 가 사라진 것 같아서 넣어줬습니다!
=> [Fix] QueryClient 사라진 문제 대응

package-lock.json, package.json, src/App.tsx, src/components/textFieldOutlined/index.stories.tsx, src/components/textFieldOutlined/index.style.tsx, src/components/textFieldOutlined/index.tsx, src/index.tsx, src/lib/GlobalStyle.ts, src/pages/diagnosis/numberButtons/durationButton/index.style.tsx, src/pages/diagnosis/numberButtons/durationButton/index.tsx, src/pages/error/index.style.tsx, src/pages/error/index.tsx, src/pages/index.tsx, yarn.lock
- resolves #105 
- **기간 선택 버튼**의 UI를 변경했습니다.
- `button`, `input`에는 **spoqahan-sans**가 적용되지 않아서 **전역 스타일**로 설정했습니다.
- `ErrorBoundary` 설정을 통해 API 에러 발생 시 **Fallback 페이지**를 구현했습니다.
=> [Refactor] 기간 버튼 UI 변경 + Error Boundary 

src/App.tsx, src/api/diagnose/fetcher.ts, src/assets/bodyParts/DigestBottomLeft.tsx, src/assets/bodyParts/DigestBottomMid.tsx, src/assets/bodyParts/DigestBottomRight.tsx, src/assets/bodyParts/DigestMidLeft.tsx, src/assets/bodyParts/DigestMidMid.tsx, src/assets/bodyParts/DigestMidRight.tsx, src/assets/bodyParts/DigestTopLeft.tsx, src/assets/bodyParts/DigestTopMid.tsx, src/assets/bodyParts/DigestTopRight.tsx, src/components/layout/index.style.tsx, src/data/answer_type.ts, src/interfaces/assets.ts, src/interfaces/diagnoseApi/diagnosis.ts, src/pages/diagnosis/answerButtons/defButton/index.tsx, src/pages/diagnosis/answerButtons/imgButton/index.style.tsx, src/pages/diagnosis/answerButtons/imgButton/index.tsx, src/pages/diagnosis/answerButtons/index.tsx, src/pages/diagnosis/answerButtons/nextButton/index.tsx, src/pages/diagnosis/index.style.tsx, src/pages/diagnosis/index.tsx, src/pages/error/index.style.tsx, src/pages/information/index.tsx, src/pages/symptomType/index.style.tsx, src/react-app-env.d.ts
- resolves #113 
- 모바일 웹에서 100vh시 스크롤이 생기는 문제를 해결하였습니다
- 귀요미 9등분이 모바일에서 깨지는 문제를 해결하였습니다
- "해당 사항이 없어요"가 포함된 질문의 사용자 인터랙션을 개선하였습니다
- 기타 자잘한 마크업을 수정했습니다
=> [Feat] 진단 로직 마크업 QA

src/api/inquiry/fetcher.ts, src/pages/appointment/hospitalDetail/index.style.tsx, src/pages/appointment/hospitalDetail/index.tsx
- #91 
- 정보 수정 요청 POST API를 연동했습니다.
=> [Feat] 정보수정요청 api 연동

src/pages/appointment/index.tsx, src/pages/appointment/search/index.tsx
- 
- 로딩창 text 수정
- 검색 debounce delay 수정
=> [Fix] 로딩창 수정

src/interfaces/challenges.ts, src/pages/challenge-stamp/index.tsx, src/pages/challenge-stamp/stamp/index.tsx
- #137 
- 현재 도장판 API 기준으로 연동했습니다.
- 도장판 상태를 성공(SUCCESS)/실패(FAILURE)/아직 오지 않은 날짜(NOTHING)로 생각하고 구현해놓기는 했는데 API 수정되고나면 요 상태도 바뀔 것 같아서 지금은 조금 이상하지만,, 추후 수정해두겠습니다.
=> [Feat] Stamp API 연동

src/App.tsx, src/api/account/service.ts, src/api/index.ts, src/components/switch/index.style.tsx, src/components/switch/index.tsx, src/hooks/account/useLogout.ts, src/pages/account/index.tsx, src/pages/account/index/index.style.tsx, src/pages/account/index/index.tsx, src/pages/account/settings/index.style.tsx, src/pages/account/settings/index.tsx, src/pages/index.tsx
- resolves #168 
- 환경설정 화면 마크업 개발했습니다.
- 로그아웃 API를 연결했습니다.
- 기타 API는 아직 안 나와서 추후 연결 예정입니다.
=> [Feat] 환경설정 화면 구현 #168

src/hooks/useModal.ts, src/pages/appointment/hospitalDetail/index.tsx, src/pages/appointment/index.style.tsx, src/pages/appointment/index.tsx, src/pages/appointment/map/refixButton.tsx, src/pages/appointment/search/index.tsx
- 없음
- Nav 바 추가
- 병원찾기 진입시 진료과 선택 모달이 처음에 뜨게 수정
- 결과 더보기 버튼 크기 수정
=> [Fix] 병원찾기 수정

src/hooks/challenge/useGetStampChart.ts, src/pages/appointment/search/index.tsx, src/pages/challenge-list/index.tsx, src/pages/challenge-stamp/index.style.tsx, src/pages/challenge-stamp/index.tsx, src/pages/challenge-stamp/stamp-grid/index.style.tsx, src/pages/challenge-stamp/stamp-grid/index.tsx, src/pages/challenge-stamp/stamp-grid/stamp.tsx
- 없음
- 챌린지 목록 불러올때 page가 -1이 되어 발생하는 오류 수정
- 도장판에서 모달이 생겼다가 사라지면 스탬프가 리렌더링되면서 도장판이 이상하게 렌더링되는 오류 수정
=> [Fix] 챌린지 목록 / 챌린지 도장판 오류 수정

src/pages/main/challenges/index.tsx, src/pages/main/hospitals/index.tsx
- 없음
- 메인페이지에서 병원 찾기 pagination 연결 및 챌린지 API를 연동했습니다.
=> [Feat] 메인페이지 병원찾기, 챌린지 API 연동

src/pages/my-challenge/index.style.tsx, src/pages/my-challenge/index.tsx
- 없음
- 디자인 수정을 이제 발견해서 일부 텍스트를  수정했습니다.
=> [Fix] 나의 챌린지 일부 텍스트 수정

src/interfaces/rewards.ts, src/pages/reward-reception/index.tsx
- 없음
- 유효기간 property가 추가되어서 api 응답 타입을 수정했습니다.
=> [Fix] reward api 응답 수정

src/components/contentHeader/index.style.tsx, src/components/contentHeader/index.tsx, src/components/layout/index.style.tsx, src/pages/diagnosis/index.style.tsx, src/pages/diagnosis/index.tsx, src/pages/diagnosisList/index.tsx, src/pages/information/index.tsx, src/pages/information/informationAgreement/index.tsx, src/pages/information/memberAgreement/index.tsx, src/pages/result/index.tsx, src/pages/result/medicinePage/medicinesList/index.style.tsx, src/pages/symptomType/index.style.tsx, src/pages/symptomType/index.tsx
- 없음
- 배경 화면이 이상하거나 스크롤이 불필요하게 있는 경우 등 일부 ui를 개선했습니다.
|감별 진단|감별 결과|
|---|---|
|![진단](https://github.com/healthier-devs/healthier-frontend/assets/76840145/c8b5c824-9874-4040-af01-abdbcf5b49ef)|![진단](https://github.com/healthier-devs/healthier-frontend/assets/76840145/a9f1fe1b-daf0-40b4-bb1d-a2543c8767a4)|
=> [Fix] 증강 감별 및 감별 결과 페이지 UI 오류 수정

src/api/account/fetcher.ts, src/api/account/service.ts, src/data/account.ts, src/interfaces/account.ts, src/pages/signUp/email/index.style.tsx, src/pages/signUp/email/index.tsx, src/pages/signUp/lib/RemoveButton.tsx, src/pages/signUp/lib/TextField.tsx, src/pages/signUp/lib/index.tsx, src/pages/signUp/password/index.tsx
- resolves #188 
- 회원가입 페이지 이메일 인증 기능을 구현했습니다.
=> [Feat] 회원가입 이메일 인증

src/App.tsx, src/api/account/fetcher.ts, src/api/account/service.ts, src/api/index.ts, src/hooks/account/useLogin.ts, src/hooks/account/useResetPassword.ts, src/hooks/account/useValidateToken.ts, src/hooks/challenge/useGetMyChallenges.ts, src/interfaces/account.ts, src/pages/account/edit/index.tsx, src/pages/account/edit/reset-password/index.tsx, src/pages/account/index.tsx, src/pages/account/index/index.tsx, src/pages/account/settings/index.style.tsx, src/pages/index.tsx, src/pages/login/default/index.tsx, src/pages/main/challenges/index.tsx, src/pages/my-challenge/index.tsx, src/pages/signUp/lib/TextField.tsx, src/state/authSlice.ts, src/state/index.ts, src/state/store.ts
- resolves #190 
- 비밀번호 재설정 페이지를 구현했습니다.
- 메인 페이지 챌린지 탭에서 로그인을 안하면 오류가 발생해서 수정해주었습니다
=> [Feat] 비밀번호 재설정 페이지

src/pages/account/settings/index.tsx, src/pages/account/settings/logout/index.tsx, src/pages/account/settings/notifications/index.tsx, src/pages/account/settings/signout/index.tsx, src/pages/account/settings/terms/index.tsx, src/pages/account/settings/version-info/index.tsx, src/pages/main/diagnosis-history/index.style.tsx, src/pages/main/diagnosis-history/index.tsx
- resolves #194 
- 환경설정에서 약관에 url 연결했스빈다
- 로그아웃 시 확인 모달을 추가했습니다
- 알림 동의 여부 API는 백엔드 API가 디벨롭 된 후 연결 예정입니다
=> [Feat] 마이페이지 계정 관련 기능

src/pages/challenge-detail/index.tsx
- 없음
- 챌린지 참여하기 할때 authenticated된 경우에만 요청이 보내질 수 있도록 수정
=> [Fix] 챌린지 참여하기 authenticated 분기 추가

src/api/index.ts, src/hooks/account/useLogin.ts, src/hooks/account/useSignUp.ts, src/hooks/diagnosis/useGetRecords.ts, src/pages/login/default/index.tsx, src/pages/main/diagnosis-history/index.tsx, src/pages/signUp/complete/index.tsx, src/pages/signUp/email/index.tsx
- resolves #200 
- 회원 가입 후 자동으로 로그인을 하도록 했습니다.
=> [Feat] 회원가입 후 자동 로그인

src/api/account/fetcher.ts, src/api/queryKeys.ts, src/hooks/account/useGetNotiSubscribed.ts, src/hooks/account/useUpdateMarketingSubscribed.ts, src/hooks/account/useValidateToken.ts, src/interfaces/account.ts, src/pages/account/settings/notifications/index.tsx, src/state/authSlice.ts
- resolves #204 
- 알림 동의 여부 변경
- validate-token API 호출 시 redux에서 email 사라지는 문제 대응
=> [Feat] 마케팅, 푸시 알림 동의 여부 변경

src/hooks/account/useGetNotiSubscribed.ts, src/hooks/account/useLogin.ts, src/state/authSlice.ts
- 
- 로그아웃 -> 재 로그인 -> 환경설정 진입 시 에러 뜨는 문제를 수정했습니다.
=> fix: 로그아웃 후 재 로그인 시 에러 뜨는 문제 대응

src/state/store.ts
쿠키가 만료돼도 localStorage에 isLoggedIn=True로 남아있는 문제 해결
- 
-
=> fix: redux store를 session storage로 변경

src/api/account/fetcher.ts, src/hooks/account/useGetNotiSubscribed.ts, src/hooks/account/useUpdateMarketingSubscribed.ts, src/hooks/account/useUpdatePushSubscribed.ts, src/interfaces/account.ts, src/pages/account/settings/notifications/index.tsx
- resolves #209 
- 푸시 알림, 마케팅 동의 api가 통합됨에 따라 수정했습니다.
- 푸시 알림 동의 여부를 변경하는 api를 연결했습니다
=> fix: 알림 동의 api 변경에 따른 수정

src/api/challenge/fetcher.ts, src/interfaces/challenges.ts, src/pages/challenge-detail/index.style.tsx, src/pages/challenge-detail/index.tsx
- 
- 챌린지가 참여 가능한 경우/가능하지 않은 경우를 나누어 버튼의 ui/이벤트 동작을 수정했습니다.
=> [Feat] 챌린지 참여 가능 여부에 따라서 버튼 이벤트/ui 수정

src/api/account/fetcher.ts, src/api/index.ts, src/hooks/account/useUserData.ts, src/interfaces/account.ts, src/pages/account/diagnose-record/index.tsx, src/pages/account/edit/index.tsx, src/pages/account/index/index.tsx
- resolves #216 
- 건강기록 레코드를 내림차순으로 정렬했습니다.
- 마이페이지 -> 프로필 수정에서 이메일을 반영했습니다.
- 프로필 사진을 제거했습니다.
=> [Fix] 마이페이지 버그

src/pages/challenge-detail/index.style.tsx, src/pages/challenge-detail/index.tsx, src/pages/challenge-detail/text-decoration/index.tsx
- resolves #147 
- 인증 가이드 텍스트 처리
- 인증 가이드 성공 / 실패 사진 처리 (PR날린 코드는 response에 사진이 있는 경우에만 보이게 해 놓았습니다)
https://github.com/healthier-devs/healthier-frontend/assets/77270547/c49981d1-0a4a-4aaf-83f8-892060e1c6ed
=> [Feat] : 챌린지 상세_가이드 사진 부분 완성

src/components/navigationBar/modal.tsx, src/hooks/rewards/useGetMyRewardRecords.ts, src/pages/appointment/hospitalDetail/index.tsx, src/pages/appointment/search/index.style.tsx, src/pages/main/symptoms/index.tsx, src/pages/reward/index.tsx
- X
- 병원 예약하기에서 로그인 모달보다 버튼이 앞으로 뜨는 현상 - 모달 zIndex 높이게 수정
- 리워드 페이지 오류 - authenticated되지 않은 경우 내 리워드 목록 불러오지 않게 수정
- 병원 운영시간 이상하게 뜨는 오류 - 빈 string 예외처리 추가
=> [Feat] 병원 예약 및 챌린지 QA 사항 반영

src/pages/appointment/hospitalDetail/index.tsx, src/pages/appointment/index.style.tsx, src/pages/appointment/search/index.style.tsx
- X
- 병원예약 페이지: 거리순 정렬 폰트 웨이트 낮추기
- 병원 상세 페이지 : 헤딩 밑에 부가정보들 폰트 색상 수정
=> [Feat] 디자인 QA 반영

src/api/account/fetcher.ts, src/api/account/service.ts, src/interfaces/account.ts, src/pages/signUp/email/index.tsx
- resolves #242 
- 회원가입 시, 인증 코드를 확인하는 api를 연결했습니다
=> feat: 인증 코드 확인 api 추가

src/pages/login/existing/LoginButton.tsx
- 기존 회원 페이지 폰트 weight를 수정했습니다.
=> fix: 기존 회원 페이지 폰트 수정

src/api/account/service.ts, src/hooks/account/useAppleLogin.ts, src/hooks/account/useGetKakaoAuth.ts, src/pages/account/sign-out/index.style.tsx, src/pages/login/kakao/index.tsx
- resolves #244 
- 탈퇴한 회원이 14일 이내 소셜 재가입하는 경우 대응
=> fix: 탈퇴 회원 재가입 대응
